services:
  quakejs:
    image: awakenedpower/quakejs-rootless:latest
    restart: always
    ports:
      - "80:8080"
      - "27960:27960"
    volumes:
      - ./server.cfg:/quakejs/base/baseq3/server.cfg
    environment:
      - HTTP_PORT=80
